config/routes.rb
Rails.application.routes.draw do
  resources :pratos do 
    resources :comentarios
  end

  root :to => "pratos#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :prato
end

app/models/prato.rb
class Prato < ActiveRecord::Base
    has_many :comentarios, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comentarios_controller.rb
class ComentariosController < InheritedResources::Base
  def create
    @prato = Prato.find(params[:prato_id])
    @comentario = @prato.comentarios.create(comentario_params)
    redirect_to prato_path(@prato)
  end

  def destroy
    @prato = Prato.find(params[:prato_id])
    @comentario = @prato.comentarios.find(params[:id])
    @comentario.destroy
    redirect_to prato_path(@prato)
  end

  def comentario_params
    params.require(:comentario).permit(:nome_usuario, :corpo, :prato_id)
  end
  
end

app/controllers/pratos_controller.rb
class PratosController < ApplicationController
  before_action :set_prato, only: [:show, :edit, :update, :destroy]

  # GET /pratos
  # GET /pratos.json
  def index
    @pratos = Prato.all
  end

  # GET /pratos/1
  # GET /pratos/1.json
  def show
  end

  # GET /pratos/new
  def new
    @prato = Prato.new
  end

  # GET /pratos/1/edit
  def edit
  end

  # POST /pratos
  # POST /pratos.json
  def create
    @prato = Prato.new(prato_params)

    respond_to do |format|
      if @prato.save
        format.html { redirect_to @prato, notice: 'Prato was successfully created.' }
        format.json { render :show, status: :created, location: @prato }
      else
        format.html { render :new }
        format.json { render json: @prato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pratos/1
  # PATCH/PUT /pratos/1.json
  def update
    respond_to do |format|
      if @prato.update(prato_params)
        format.html { redirect_to @prato, notice: 'Prato was successfully updated.' }
        format.json { render :show, status: :ok, location: @prato }
      else
        format.html { render :edit }
        format.json { render json: @prato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pratos/1
  # DELETE /pratos/1.json
  def destroy
    @prato.destroy
    respond_to do |format|
      format.html { redirect_to pratos_url, notice: 'Prato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prato
      @prato = Prato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prato_params
      params.require(:prato).permit(:nome, :descricao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/pratos_helper.rb
module PratosHelper
end

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario, local: true) do |form| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
        <% comentario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome_usuario %>
    <%= form.text_field :nome_usuario %>
  </div>

  <div class="field">
    <%= form.label :corpo %>
    <%= form.text_area :corpo %>
  </div>

  <div class="field">
    <%= form.label :prato_id %>
    <%= form.text_field :prato_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome usuario</th>
      <th>Corpo</th>
      <th>Prato</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.nome_usuario %></td>
        <td><%= comentario.corpo %></td>
        <td><%= comentario.prato_id %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome usuario:</strong>
  <%= @comentario.nome_usuario %>
</p>

<p>
  <strong>Corpo:</strong>
  <%= @comentario.corpo %>
</p>

<p>
  <strong>Prato:</strong>
  <%= @comentario.prato_id %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
<body background="fundo.png">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div ID="titulo">
            <a class="brand" href="/" id="meulink"><h1>Festival Gastronômico da FGA</h1></font></a>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pratos/_form.html.erb
<%= form_with(model: prato, local: true) do |form| %>
  <% if prato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prato.errors.count, "error") %> prohibited this prato from being saved:</h2>

      <ul>
        <% prato.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pratos/edit.html.erb
<h1>Editing Prato</h1>

<%= render 'form', prato: @prato %>

<%= link_to 'Show', @prato %> |
<%= link_to 'Back', pratos_path %>

app/views/pratos/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Pratos</h2>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pratos.each do |prato| %>
      <tr>
        <td><%= prato.nome %></td>
        <td><%= prato.descricao %></td>
        <td><%= link_to 'Show', prato %></td>
        <td><%= link_to 'Edit', edit_prato_path(prato) %></td>
        <td><%= link_to 'Destroy', prato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prato', new_prato_path %>

app/views/pratos/new.html.erb
<h1>New Prato</h1>

<%= render 'form', prato: @prato %>

<%= link_to 'Back', pratos_path %>

app/views/pratos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @prato.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @prato.descricao %>
</p>

<h2>Comentarios</h2>
<% @prato.comentarios.each do |comentario| %>
  <p>
    <b>Usuário:</b>
    <%= comentario.nome_usuario %>
  </p>

  <p>
    <b>Comentario:</b>
    <%= comentario.corpo %>
  </p>

  <%= link_to 'Editar', edit_prato_comentario_path(@prato.comentarios) %>
  <hr />
<% end %>

<h2>Adicione um comentario:</h2>
<%= form_for([@prato, @prato.comentarios.build]) do |f| %>
  <div class="field">
    <%= f.label :nome_usuario %><br />
    <%= f.text_field :nome_usuario %>
  </div>
  <div class="field">
    <%= f.label :corpo %><br />
    <%= f.text_area :corpo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 
<br />

<%= link_to 'Edit', edit_prato_path(@prato) %> |
<%= link_to 'Back', pratos_path %>